# -*- coding: utf-8 -*-
"""Treasure Island.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ooMwLssohlVo74AxUDUIk949r185RAo
"""

import streamlit as st

st.set_page_config(page_title="Karibu Treasure Island", page_icon="🌴")

st.title("~ Karibu to Treasure Island ~")
st.write('''
Where fortunes await and foolishness gets roasted.
Type wisely. The ancestors are watching.
''')

# Add island ASCII art
st.markdown('''
```
                      /\
                     /**\
                    /****\   ~ Karibu to Treasure Island ~
                   /######\
                  /########\
        ________/##########\_______
       |__   Can you survive this   __|
          |  or will you just become |
          |     another village tale? |
          |___________________________|
```
''')

# Game flow using session state
if 'step' not in st.session_state:
    st.session_state.step = 'crossroad'

if st.session_state.step == 'crossroad':
    st.subheader("You are at a cross road.")
    user_direction = st.radio("Which direction will you take?", ('left', 'right'))
    if st.button("Proceed"):
        if user_direction == 'right':
            st.error("You stepped right into a hole deeper than your ancestors' wisdom. Ah! Game Over, my friend!")
            st.session_state.step = 'end'
        else:
            st.session_state.step = 'lake'

elif st.session_state.step == 'lake':
    st.subheader("You've reached a vast lake. There's an island in the middle.")
    user_action_lake = st.radio("What will you do?", ('wait', 'swim'))
    if st.button("Continue"):
        if user_action_lake == 'swim':
            st.error("You swam like a fish... until the fish got jealous. Ambushed by angry tilapia and their catfish cousins. Game Over!")
            st.session_state.step = 'end'
        else:
            st.success("Patience paid off! A mysterious boat appeared, rowed by a quiet uncle humming old school tunes.")
            st.session_state.step = 'doors'

elif st.session_state.step == 'doors':
    st.subheader("You arrive at a hut with 3 magical doors:")
    st.markdown('''
    ```
    🔗 Red Door     🔗 Blue Door     🔗 Yellow Door
    ```
    ''')
    user_door_choice = st.selectbox("Which door do you choose?", ('red', 'blue', 'yellow'))
    if st.button("Open Door"):
        if user_door_choice == 'red':
            st.error("You opened the red door and were roasted like Sunday nyama choma. Fire said 'Welcome'. Game Over!")
            st.session_state.step = 'end'
        elif user_door_choice == 'yellow':
            st.balloons()
            st.success("You found the treasure! You’re now richer than a Nairobi landlord. Drinks on you! You Win!")
            st.session_state.step = 'end'
        elif user_door_choice == 'blue':
            st.error("You entered like a boss, but inside was a full-blown animal AGM—lions roaring, hyenas giggling, and Mufasa’s cousin licking his lips. Guess who’s dinner? Game Over!")
            st.session_state.step = 'end'

elif st.session_state.step == 'end':
    st.subheader("Game Over")
    if st.button("Play Again"):
        st.session_state.step = 'crossroad'

